server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    # FUERZA LA RUTA CORRECTA
    root   /usr/share/nginx/html;
    index  index.html;

    location / {
        # Intenta servir el archivo, luego la carpeta, 
        # y si no, salta al index.html de la RAÍZ
        try_files $uri $uri/ /index.html;
    }

    # Prevenir errores de tipos MIME (CSS/JS)
    include /etc/nginx/mime.types;

    # OPCIONAL: Para ver qué pasa realmente, activamos el log de error detallado
    error_log /var/log/nginx/error.log debug;
}